spc-group/haven

src/conftest.py, src/haven/iconfig_testing.toml, src/haven/instrument/ion_chamber.py, src/haven/motor_position.py, src/haven/tests/test_ion_chamber.py
Previously, we assumed the clock frequency for channel 1 was the same as the max frequency of the V-to-F source (e.g. V2F100), and that the max V-to-F is 10V. This change removes that assumption, and the max source frequency and max voltage of the V-to-F are now an iconfig parameter (counts_per_volt_second).
=> Re-wrote the ion chamber scaler counts-to-volts calculation.

src/firefly/application.py, src/firefly/launcher.py, src/firefly/main_window.py, src/firefly/plans/line_scan.py, src/firefly/plans/move_motor_window.py, src/firefly/plans/xafs_scan.py, src/firefly/queue_button.py, src/firefly/queue_client.py, src/firefly/tests/test_main_window.py, src/firefly/tests/test_queue_button.py, src/firefly/tests/test_queue_client.py, src/firefly/tests/test_xafs_scan.py, src/haven/exceptions.py, src/haven/instrument/ion_chamber.py, src/haven/instrument/motor.py
Finished out the run engine control actions, plus the ability to request the queue stop after the current scan. Status bar now shows how many items are in the queue. Autostart action responds to changes in the queueserver's autostart state. Bunch of other UX improvements too.
=> UX improvements for queueserver controls in Firefly

src/firefly/application.py, src/firefly/energy.py, src/firefly/energy.ui, src/firefly/launcher.py, src/firefly/motor.ui, src/firefly/queue_client.py, src/firefly/tests/test_energy_display.py, src/firefly/tests/test_tweak.py, src/firefly/tweak.py, src/firefly/tweak.ui, src/haven/iconfig_testing.toml, src/haven/instrument/energy_positioner.py, src/haven/instrument/ion_chamber.py, src/haven/instrument/load_instrument.py, src/haven/instrument/monochromator.py, src/haven/instrument/xray_source.py, src/haven/tests/test_energy_positioner.py, src/haven/tests/test_iconfig.py, src/haven/tests/test_monochromator.py, src/haven/tests/test_xray_source.py
Refactor of the energy positioner. Waiting on real hardware controls to be available.
=> Energy widgets

src/haven/catalog.py, src/haven/instrument/__init__.py, src/haven/instrument/motor.py, src/haven/motor_position.py, src/haven/tests/test_save_motor_positions.py
Previously, saved motor positions resided in their own database collection. This PR re-factors the save motor position support to use bluesky plans. This will mean we don't need to maintain a separate database collection.
Also uses rich to format the printed motor positions:
There's a new function ``get_motor_positions()`` which will query the database for a list of motor positions based on when they were recorded. Useful for the Firefly support. To make the Firefly support more fluid, these functions are asynchronous.
All this support only works with ophyd-async devices. This means the remaining vanilla ophyd devices will not work. Also, I think the robot support uses the ``rbv()`` function from this module. We should think about whether this still works. The tests still pass so …
=> Use bluesky plans when saving motor positions

environment.yml, src/haven/instrument/motor.py, src/haven/instrument/srs570.py, src/haven/motor_position.py, src/haven/tests/test_save_motor_positions.py
I made this using the ``Regex()`` query. One thing I couldn't test was how pyQt handles escape characters. If we put "\n" into a label and read it, do we get a newline or a '\\' and a 'n' (we want the second one). 
See paragraph 4 [here](https://docs.python.org/3/library/re.html) for more details.
=> Added ability to filter saved motor positions by name.

src/firefly/run_browser.ui, src/firefly/status.py, src/haven/devices/motor.py, src/haven/devices/shutter.py, src/haven/devices/signal.py, src/haven/iconfig_testing.toml, src/haven/instrument.py, src/haven/positioner.py, src/haven/tests/test_shutter.py
=> Async shutters

src/haven/devices/energy_positioner.py, src/haven/positioner.py, src/haven/tests/test_energy_positioner.py
=> energy positioner disables mono-ID tracking before setting energy

environment.yml, pyproject.toml
Minimum ophyd-async version is now 0.8.0a5.
=> Updated dependencies to new ophyd-async release.

src/haven/devices/ion_chamber.py, src/haven/tests/test_ion_chamber.py
This PR adds a proper timeout calculation to the ``IonChamber.trigger()`` method. Previously, the default timeout was used regardless of the settings on the scaler. Now, the new method ``IonChamber.default_timeout()`` is used to determine the best timeout based on the scaler configuration.
=> Ion chamber timeout

src/haven/devices/srs570.py, src/haven/positioner.py, src/haven/tests/test_srs570.py
The next version of ophyd-async will enforce capitalization for attributes on enum types. Currently, these are recommended by convention, and so doing this now shouldn't cause any backwards compatibility issues.
- ~write docs~
=> Converted ophyd enum types to uppercase.

environment.yml, src/firefly/tests/test_grid_scan_window.py, src/firefly/tests/test_line_scan_window.py, src/haven/tests/test_energy_positioner.py, src/haven/tests/test_ion_chamber.py, src/haven/tests/test_motor.py, src/haven/tests/test_positioner.py, src/haven/tests/test_save_motor_positions.py, src/haven/tests/test_shutter.py, src/haven/tests/test_signal.py, src/haven/tests/test_srs570.py, src/haven/tests/test_xray_source.py
Recently, ophyd-async moved the mock-signal utilities to a new module ``testing``: https://github.com/bluesky/ophyd-async/pull/695
This PR updates our tests to use this new module structure. No production code was changed.
- ~write docs~
=> Updated tests to use the new ``testing`` module from ophyd-async.

src/haven/devices/xray_source.py
Fixes https://github.com/spc-group/haven/issues/317
- ~write docs~
=> Removed the *min_move* argument from the undulator positioner.

environment.yml, src/firefly/tests/test_voltmeters.py, src/firefly/voltmeters.py, src/firefly/voltmeters.ui
=> Added back the shutter selector to the voltmeters display.

src/firefly/plans/grid_scan.py, src/firefly/plans/grid_scan.ui, src/firefly/plans/line_scan.py, src/firefly/plans/line_scan.ui, src/firefly/plans/regions_display.py, src/firefly/tests/test_grid_scan_window.py, src/firefly/tests/test_line_scan_window.py
=> Plan window improvement

environment.yml, src/conftest.py, src/firefly/run_browser/client.py, src/firefly/run_browser/display.py, src/firefly/run_browser/tests/test_display.py, src/firefly/run_browser/widgets.py, src/haven/catalog.py, src/haven/devices/labjack.py, src/haven/devices/motor.py, src/haven/iconfig_testing.toml, src/haven/ipython_startup.ipy, src/haven/motor_position.py, src/haven/plans/fly.py, src/haven/plans/record_dark_current.py, src/haven/plans/robot_transfer_sample.py, src/haven/preprocessors.py, src/haven/run_engine.py, src/haven/tests/test_catalog.py, src/haven/tests/test_energy_xafs_scan.py, src/haven/tests/test_iconfig.py, src/haven/tests/test_labjack.py, src/haven/tests/test_motor.py, src/haven/tests/test_preprocessors.py, src/haven/tests/test_record_dark_current_plan.py, src/haven/tests/test_run_engine.py, src/haven/tests/test_save_motor_positions.py, src/haven/tests/test_scaler.py, src/queueserver/tiled_consumer.py
The bluesky project is moving from storing raw scan documents in a mongo database via databroker to storing tabular data in a Tiled catalog backed by a relational (sqlite or postgres) database. This PR updates Haven and Firefly to use the Tiled catalog by default.
This change is necessary to **enable ophyd-async detector** data to be read back out by Tiled.
The aim with this PR is keep top-level features (e.g. run browser) the same as with the old database structure. This PR does *not* add features that will be useful with the new catalog, such as filtering by beamline; these will be added in a separate PR.
To **avoid losing data**, the raw documents should still be saved in the mongo database. This way, when we are ready to fully switch over we will create a new tiled catalog and stream …
=> Move from mongodb to tiled-backed catalog

src/firefly/controller.py, src/haven/catalog.py, src/haven/devices/area_detector.py, src/haven/iconfig_testing.toml, src/haven/ipython_startup.ipy, src/queueserver/tiled_consumer.py
Right now, the Tiled client information is stored in iconfig.toml, including the API key. The easiest way to get rid of this is to give each user its own Tiled profiles. This PR updates Haven to use Tiled profiles by default.
=> Converted the tiled_client factory to use Tiled profiles.

src/firefly/controller.py, src/firefly/run_browser/display.py, src/firefly/run_browser/run_browser.ui
Firefly's run browser can export scans through Tiled. If Tiled fails to export a scan, the error was only present in the Firefly console. This PR adds a QErrorMessage that reports to the operator that the export failed.
- ~add tests~
- ~write docs~
=> Added an error dialog for showing export errors in run browser.

docs/topic_guides/area_detectors.rst, src/haven/devices/__init__.py, src/haven/devices/area_detector.py, src/haven/devices/detectors/eiger.py, src/haven/devices/detectors/xspress.py, src/haven/iconfig_testing.toml, src/haven/instrument.py, src/haven/tests/test_eiger.py
This PR adds support for (at least version 1) Eiger area detectors. Tested against the Eiger 500K.
=> Ophyd-async support for Eiger area detectors

src/haven/devices/detectors/xspress.py, src/haven/tests/test_xspress.py
We noticed that the xspress device was always named ``"hdf"`` regardless of what the *name* parameter was. This was fixed if the HDF file IO device was removed from the *plugins* parameter. It is not needed since ``xspress.fileio`` is the same thing and is handled specially since it's tied in the writer. This PR removes the HDF fileio from *plugins* and updates a few other things to match the way ophyd-async prefers area detectors to work now.
- ~write docs~
=> Re-factored the xspress device to avoid redundant HDF plugins.

environment.yml, pyproject.toml, src/haven/ipython_startup.ipy, src/haven/motor_position.py, src/haven/tests/test_instrument_registry.py, src/queueserver/queueserver_startup.py
=> Updates to work with ophyd-registry v2.0.0

src/haven/devices/detectors/xspress.py, src/haven/tests/test_xspress.py
Need to write a test that confirms the NDAttributes are being written properly.
- ~write docs~
=> Restored Xspress NDattributes.

src/haven/devices/shutter.py
The PSS shutter is a positioner. This means that it waits for the readback value to match the setpoint before returning control to the calling context.
Each positioner has a `precision` signal. When setting a value, the positioner considers the readback to match the setpoint when they are within `10**(-precision)` of each other.
If the precision is `0`, then the positioner will wait until the readback value is within ±1 of the setpoint. For a motor this makes sense. For the shutter, `0` and `1` are the open and closed states.
For the shutter, the precision was set to `0`, so if the shutter is open (`0`), when doing…
```python
await shutter.set(1)
```
…the shutter will check that the current position is between 0 and 2 (`1±1`), which it always will be and so the call returns immediately. …
=> FIX: PSS shutter device should now wait properly

src/haven/devices/ion_chamber.py, src/haven/tests/test_ion_chamber.py
In response to a recent discussion, this PR tweaks the signals on the ion chambers.
Each ion chamber now has a new signal: `I0.count_rate` that is the same as the scaler's `net_count` signal, but corrected for the true acquire time of the scaler.
The hinted signals are also tweaked so that each ion chamber has the following hinted signals:
- "I0-count"
- "I0-count_rate"
These replace the previous hinted signal of "I0-net_current".
---
- ~write docs~
=> Ion chambers now have count_rate signals and new hints.

src/firefly/queue_client.py, src/firefly/tests/test_controller.py
=> Removed the bluesky queueserver API from Firefly controller tests.
