spc-group/haven

haven/__init__.py
haven/plans/set_energy.py
tests/test_set_energy.py

ENH: Revised set_energy plan for changing mono and ID.

---

haven/motor_position.py
tests/fixtures/motor_positions.yaml
tests/test_save_motor_positions.py

Add _savetime_ only to _save_motor_position_ and _list_motor_positions_

Add savetime feature to MotorPosition.

---

haven/iconfig_default.toml
haven/instrument/ion_chamber.py
tests/test_ion_chamber.py

Infer pre-amp prefix from scaler channel number.

---

src/conftest.py
src/haven/__init__.py
src/haven/iconfig_testing.toml
src/haven/instrument/__init__.py
src/haven/instrument/load_instrument.py
src/haven/instrument/robot.py
src/haven/tests/test_robot.py

Add robot ophyd and tests. The code test and the device test at 25-ID-C have passed.

Austin ophyd

---

src/firefly/run_browser.py
src/firefly/run_client.py
src/firefly/tests/test_run_browser.py
src/haven/catalog.py

Restored some functionality to the run browser after re-factoring Firefly.
There's a new conext manager for handling the UI hints during long DB operations.

Run browser updates

---

src/haven/instrument/area_detector.py
src/haven/instrument/camera.py

Support Single ImageMode for cameras

---

src/firefly/controller.py
src/firefly/main_window.py
src/firefly/plans/grid_scan.py
src/firefly/plans/grid_scan.ui
src/firefly/plans/line_scan.py
src/firefly/plans/move_motor_window.py
src/firefly/plans/move_motor_window.ui
src/firefly/plans/regions_display.py
src/firefly/plans/util.py
src/firefly/plans/xafs_scan.ui
src/firefly/queue_client.py
src/firefly/tests/test_grid_scan_window.py
src/firefly/tests/test_line_scan_window.py
src/firefly/tests/test_move_motor_window.py
src/firefly/tests/test_xafs_scan.py
src/haven/instrument/aps.py

number of scan pnts in each of the region in gridscan

Gridscan fix

---

environment.yml
ipython_startup.py
pyproject.toml
src/firefly/pydm_plugin.py
src/haven/__init__.py
src/haven/run_engine.py

We could soon start incorporating ophyd-async as devices. This PR doesn't add any ophyd-async devices, but prepares the rest of the repository to use them as best as possible.

Prepare for writing ophyd-async devices

---

pyproject.toml
src/firefly/controller.py
src/firefly/exceptions.py
src/firefly/launcher.py
src/firefly/motor.py
src/firefly/pydm_plugin.py
src/firefly/tests/test_pydm_plugin.py

Still pretty basic, but enough to keep the beamline running while setting up more ophyd-async devices.

A PyDM plugin that works with ophyd-async

---

src/firefly/component_selector.py
src/firefly/tests/test_component_selector.py

Related to https://github.com/spc-group/haven/issues/257, but I don't think it necessarily fixes it.

Component selector now returns None if no component is selected.

---

src/firefly/energy.py
src/firefly/queue_client.py
src/firefly/tests/test_energy_display.py
src/firefly/tests/test_queue_client.py
src/firefly/tests/test_table.py
src/haven/devices/energy_positioner.py
src/haven/devices/monochromator.py
src/haven/devices/signal.py
src/haven/devices/xray_source.py
src/haven/iconfig_testing.toml
src/haven/instrument.py
src/haven/ipython_startup.ipy
src/haven/plans/energy_scan.py
src/haven/positioner.py
src/haven/tests/test_energy_positioner.py
src/haven/tests/test_energy_xafs_scan.py
src/haven/tests/test_instrument.py
src/haven/tests/test_monochromator.py
src/haven/tests/test_positioner.py
src/haven/tests/test_signal.py
src/haven/tests/test_xray_source.py

Async energy positioner

---

src/firefly/controller.py
src/haven/devices/energy_positioner.py
src/haven/devices/xray_source.py
src/haven/ipython_startup.ipy
src/haven/positioner.py
src/haven/tests/test_energy_positioner.py
src/haven/tests/test_positioner.py
src/haven/tests/test_preprocessors.py
src/haven/tests/test_xray_source.py
src/queueserver/systemd_units/mongo_consumer.service
src/queueserver/systemd_units/queueserver.service
src/queueserver/systemd_units/redis.service

Async energy

---

.readthedocs.yaml
pyproject.toml
src/haven/devices/xray_source.py
src/haven/plans/fly.py
src/haven/positioner.py
src/haven/tests/test_ion_chamber.py
src/haven/tests/test_positioner.py

Fix id positioner

---

src/firefly/run_browser.ui
src/haven/plans/energy_scan.py
src/haven/plans/xafs_scan.py

Fixes to the energy scan plans

---

src/firefly/plans/xafs_scan.py
src/firefly/plans/xafs_scan.ui
src/firefly/tests/test_xafs_scan.py

This fixed the run_button issue and changed the default EXAFS regions #283

Improved usability for the xafs scan window

---

pyproject.toml
src/firefly/plans/line_scan.py
src/firefly/tests/test_line_scan_window.py
src/haven/devices/ion_chamber.py
src/haven/devices/motor.py
src/haven/tests/test_utils.py
src/haven/utils.py

Name mangling

---

src/haven/devices/area_detector.py
src/haven/plans/__init__.py
src/haven/plans/_energy_scan.py

Causes a bug as described here: https://github.com/spc-group/haven/issues/359

Removed baseline decorator from the auto_gain plan.

---

mime/x-xdi.xml

This MIME-type is already installed on the s25idcuser account, this PR just gets it into the main repository.

Added a MIME-type definition for XDI files.

---

src/haven/devices/detectors/eiger.py

Added a default deadtime to the Eiger detector.

---

src/haven/ipython_startup.ipy
src/queueserver/queueserver_startup.py

added a check for importing devices that are named the same as their parent

---

src/firefly/xrf_detector.ui

xrf viewer change from drv to driver

---

pyproject.toml
src/haven/devices/blade_slits.py
src/haven/tests/test_blade_slits.py

Added hinted signals to the blade slits positioners.
